### PR TITLE
WIP PR for GA release

### PR DESCRIPTION
**Pull request by owocki**
Pr of @john-brunelle 's work

### CODE REVIEW

**Comment by mbeacom** [comment]
@owocki I'll take a little bit of time later and check this out in xcode.

**Comment by owocki** [comment]
getting these two errors when trying to compile on xcode 9.2 (9C40b)

```
/Users/kevinowocki/Sites/gitcoin/ios/Gitcoin/Gitcoin-Bridging-Header.h:12:9: 'PHFComposeBarView/PHFComposeBarView.h' file not found

Failed to emit precompiled header '/Users/kevinowocki/Library/Developer/Xcode/DerivedData/Gitcoin-egufuruptgtsnvbepcrtyicupmzi/Build/Intermediates.noindex/PrecompiledHeaders/Gitcoin-Bridging-Header-swift_2F7AQ19GP2L7R-clang_35FWCSIC74Z2B.pch' for bridging header '/Users/kevinowocki/Sites/gitcoin/ios/Gitcoin/Gitcoin-Bridging-Header.h'
````

**Comment by owocki** [comment]
@john-brunelle have you seen these build errors before?

**Comment by owocki** [comment]
not having any luck with [this SO answer](https://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files/12142790#12142790) gonna move on to something else now

**Comment by owocki** [comment]
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/ios~ % pod update
Update all pods
Updating local specs repositories
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

```

i seem to be getting this error when i update my pods, though i am on line.

so i followed [this stackoverflow answer](https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo) and did

```
pod repo remove master
pod setup
pod install
```

but am still getting build errors

**Comment by owocki** [comment]
@john-brunelle i'd also just be happy to test via testflight (my email is already on the distro list in itunes connect).  is that a viable path?

**Comment by owocki** [comment]
hmm.. looks like updating ruby / cocoapods, and then doing a `pod update` helped with the above error.. but I still get the build error

**Comment by owocki** [comment]
looks like [stackoverflow says](https://stackoverflow.com/questions/45779591/failed-to-emit-precompiled-header-for-bridging-header) that [this area of build settings](http://bits.owocki.com/15112Q151l1l/Screen%20Shot%202018-04-16%20at%2011.48.50%20AM.png) is important for some reason.. what are you settings here?

**Comment by owocki** [comment]
xcode is `Version 9.2 (9C40b)`

**Comment by owocki** [comment]
fd8ea48cb0a031772bdc0f9b139aaaa85f41d567 fixed it!

**Comment by owocki** [comment]
@john-brunelle i've got some feedback on the app / UI for you [here](https://github.com/gitcoinco/ios/issues/20)

**Pull request merged**
